# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-15 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumb',
            field=models.ImageField(blank=True, default='SPACE.png', upload_to=b''),
        ),
    ]
